---

alias: Turn off basement light 10 minute after last movement
trigger:
- platform: state
  entity_id: binary_sensor.basement_occupancy
  to: 'off'
  for:
    minutes: 10
- platform: state
  entity_id: binary_sensor.basement_stairs_occupancy
  to: 'off'
  for:
    minutes: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.basement_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.basement_stairs_occupancy
      state: 'off'
action:
- service: light.turn_off
  entity_id:
  - light.basement_ceiling_1
  - light.basement_ceiling_2
  - light.basement_ceiling_3
  - light.basement_ceiling_4
  - light.basement_ceiling_5
