---

alias: Turn on Christmas lights 30 minutes before dusk
trigger:
- platform: sun
  event: sunset
  offset: "-00:30:00"
action:
- service: switch.turn_on
  entity_id:
  - switch.christmas_indoor_light_1
  - switch.christmas_indoor_light_2
  - switch.christmas_porch_light
  - switch.christmas_tree_light
