---

alias: Turn on Garage lights when Person is detected
trigger: 
  platform: state
  entity_id: binary_sensor.garage_person
  from: 'off'
  to: 'on'
action:
- service: light.turn_on
  entity_id:
  - light.garage_ceiling
